const list = [
    {
        path: '/',
        redirect:"/login"
    },{
        path: '/login',
        name: 'login',
        meta:{
            title:"登陆"
        },
        component: () => import('@/components/login/login.vue')
    },{
        path:"/lingdaoren",
        name:"lingdaoren",
        meta:{
            title:"领导人信息"
        },
        component:()=>import('@/components/lingdaoren.vue')
    },{
        path:'/tuoguanset',
        name:"tuoguanset",
        meta:{
            title:"托管设置"
        },
        component:()=>import('@/components/tuoguanset.vue')
    },{
        path:'/chengxinpaihang',
        name:"chengxinpaihang",
        meta:{
            title:"诚信值排行"
        },
        component:()=>import('@/components/chengxinpaihang.vue')
    },{
        path:'/zhuanpan',
        name:"zhuanpan",
        meta:{
            title:"幸运大转盘"
        },
        component:()=>import('@/components/zhuanpan.vue')
    },{
        path:'/zhongjiangjilv',
        name:"zhongjiangjilv",
        meta:{
            title:"中奖纪录"
        },
        component:()=>import('@/components/zhongjiangjilv.vue')
    },{
        path:'/xiugaimima',
        name:"xiugaimima",
        meta:{
            title:"修改密码"
        },
        component:()=>import('@/components/xiugaimima.vue')
    },{
        path:'/wentiask/:id',
        name:"wentiask",
        meta:{
            title:"常见问题"
        },
        component:()=>import('@/components/wentiask.vue')
    },{
        path:'/wentilist',
        name:"wentilist",
        meta:{
            title:"常见问题"
        },
        component:()=>import('@/components/wentilist.vue')
    },{
        path:'/zhuanshukefu',
        name:"zhuanshukefu",
        meta:{
            title:"专属客服"
        },
        component:()=>import('@/components/zhuanshukefu.vue')
    },{
        path:'/gonggaomes',
        name:"gonggaomes",
        meta:{
            title:"公告信息"
        },
        component:()=>import('@/components/gonggaomes.vue')
    },{
        path:'/gerenmes',
        name:"gerenmes",
        meta:{
            title:"个人信息"
        },
        component:()=>import('@/components/gerenmes.vue')
    },{
        path:'/xinvip',
        name:"xinvip",
        meta:{
            title:"新会员注册"
        },
        component:()=>import('@/components/xinvip.vue')
    },{
        path:'/yinhangka',
        name:"yinhangka",
        meta:{
            title:"银行卡"
        },
        component:()=>import('@/components/yinhangka.vue')
    },{
        path:'/zhuce/:id',
        name:"zhuce",
        meta:{
            title:"注册"
        },
        component:()=>import('@/components/zhuce.vue')
    },{
        path:'/jifenmingxi',
        name:"jifenmingxi",
        meta:{
            title:"积分明细"
        },
        component:()=>import('@/components/jifenmingxi.vue')
    },{
        path:'/jianglimingxi',
        name:"jianglimingxi",
        meta:{
            title:"奖励明细"
        },
        component:()=>import('@/components/jianglimingxi.vue')
    },{
        path:'/liximingxi',
        name:"liximingxi",
        meta:{
            title:"利息明细"
        },
        component:()=>import('@/components/liximingxi.vue')
    },{
        path:'/zhaohuimima',
        name:"zhaohuimima",
        meta:{
            title:"找回密码"
        },
        component:()=>import('@/components/zhaohuimima.vue')
    },{
        path:'/jiaoyitixing',
        name:"jiaoyitixing",
        meta:{
            title:"交易提醒"
        },
        component:()=>import('@/components/jiaoyitixing.vue')
    },{
        path:'/ruhechu/:id',
        name:"ruhechu",
        meta:{
            title:"详情"
        },
        component:()=>import('@/components/ruhechu.vue')
    },{
        path:'/tabbar',
        name:"tabbar",
        component:()=>import("@/components/tabbar.vue"),
        children:[{
            path:'/index',
            name:'index',
            component:()=>import("@/components/index.vue"),
            meta:{
                title:""
            }
        },{
            path:'/tuandui',
            name:"tuandui",
            meta:{
                title:"我的团队"
            },
            component:()=>import('@/components/tuandui.vue')
        },{
            path:'/zhanghu',
            name:"zhanghu",
            meta:{
                title:"账户"
            },
            component:()=>import('@/components/zhanghu.vue')
        },{
            path:'/geren',
            name:"geren",
            meta:{
                title:"我的"
            },
            component:()=>import('@/components/geren.vue')
        }]
    },{
        path:"/xieyi",
        name:'xieyi',
        meta:{
            title:"用户协议"
        },
        component:()=>import('@/components/yonghuxieyi.vue')
    },{
        path:"/guize",
        name:'guize',
        meta:{
            title:"抽奖规则"
        },
        component:()=>import('@/components/choujiangxieyi.vue')
    },{
        path:"/chengxinmingxi",
        name:'chengxinmingxi',
        meta:{
            title:"诚信值明细"
        },
        component:()=>import('@/components/chengxinmingxi.vue')
    },{
        path:"/shoplist",
        name:'shoplist',
        meta:{
            title:"商品"
        },
        component:()=>import('@/components/shoplist.vue')
    }
    
]

export default list;